const actionType = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  REMOVE_CART: 'REMOVE_CART',
  REMOVE_ONE_ITEM_FROM_CART: 'REMOVE_ONE_ITEM_FROM_CART',
  UPDATE_COLLECTION: 'UPDATE_COLLECTION',
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAIL: 'FETCH_COLLECTION_FAIL',
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAIL: 'SIGN_OUT_FAIL',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL'
};

export default actionType;
